// Generated by `npm run themes -- index` from the JSON files in this folder. Do not edit.

import gruvboxDarkHard from './gruvbox-dark-hard.json' with { type: 'json' };
import gruvboxDarkMedium from './gruvbox-dark-medium.json' with { type: 'json' };
import gruvboxDarkSoft from './gruvbox-dark-soft.json' with { type: 'json' };
import gruvboxLightHard from './gruvbox-light-hard.json' with { type: 'json' };
import gruvboxLightMedium from './gruvbox-light-medium.json' with { type: 'json' };
import gruvboxLightSoft from './gruvbox-light-soft.json' with { type: 'json' };
import catppuccinFrappe from './catppuccin-frappe.json' with { type: 'json' };
import catppuccinMacchiato from './catppuccin-macchiato.json' with { type: 'json' };
import catppuccinMocha from './catppuccin-mocha.json' with { type: 'json' };
import catppuccinLatte from './catppuccin-latte.json' with { type: 'json' };
import tokyoNight from './tokyo-night.json' with { type: 'json' };
import tokyoNightMoon from './tokyo-night-moon.json' with { type: 'json' };
import tokyoNightStorm from './tokyo-night-storm.json' with { type: 'json' };
import tokyoNightDay from './tokyo-night-day.json' with { type: 'json' };
import dracula from './dracula.json' with { type: 'json' };
import draculaAlucard from './dracula-alucard.json' with { type: 'json' };
import nord from './nord.json' with { type: 'json' };
import solarizedDark from './solarized-dark.json' with { type: 'json' };
import solarizedLight from './solarized-light.json' with { type: 'json' };
import oneDark from './one-dark.json' with { type: 'json' };
import oneLight from './one-light.json' with { type: 'json' };
import rosePine from './rose-pine.json' with { type: 'json' };
import rosePineMoon from './rose-pine-moon.json' with { type: 'json' };
import rosePineDawn from './rose-pine-dawn.json' with { type: 'json' };
import githubDark from './github-dark.json' with { type: 'json' };
import githubDarkDimmed from './github-dark-dimmed.json' with { type: 'json' };
import githubDarkHighContrast from './github-dark-high-contrast.json' with { type: 'json' };
import githubLight from './github-light.json' with { type: 'json' };
import githubLightHighContrast from './github-light-high-contrast.json' with { type: 'json' };
import kanagawaDragon from './kanagawa-dragon.json' with { type: 'json' };
import kanagawaWave from './kanagawa-wave.json' with { type: 'json' };
import kanagawaLotus from './kanagawa-lotus.json' with { type: 'json' };
import everforestDarkHard from './everforest-dark-hard.json' with { type: 'json' };
import everforestDarkMedium from './everforest-dark-medium.json' with { type: 'json' };
import everforestDarkSoft from './everforest-dark-soft.json' with { type: 'json' };
import everforestLightHard from './everforest-light-hard.json' with { type: 'json' };
import everforestLightMedium from './everforest-light-medium.json' with { type: 'json' };
import everforestLightSoft from './everforest-light-soft.json' with { type: 'json' };
import monokai from './monokai.json' with { type: 'json' };
import ayuDark from './ayu-dark.json' with { type: 'json' };
import ayuMirage from './ayu-mirage.json' with { type: 'json' };
import ayuLight from './ayu-light.json' with { type: 'json' };
import nightOwl from './night-owl.json' with { type: 'json' };
import lightOwl from './light-owl.json' with { type: 'json' };
import material from './material.json' with { type: 'json' };
import materialDarker from './material-darker.json' with { type: 'json' };
import materialDeepOcean from './material-deep-ocean.json' with { type: 'json' };
import materialOceanic from './material-oceanic.json' with { type: 'json' };
import materialPalenight from './material-palenight.json' with { type: 'json' };
import materialLighter from './material-lighter.json' with { type: 'json' };
import tomorrowNight from './tomorrow-night.json' with { type: 'json' };
import tomorrowNightBlue from './tomorrow-night-blue.json' with { type: 'json' };
import tomorrowNightBright from './tomorrow-night-bright.json' with { type: 'json' };
import tomorrowNightEighties from './tomorrow-night-eighties.json' with { type: 'json' };
import tomorrow from './tomorrow.json' with { type: 'json' };
import carbonfox from './carbonfox.json' with { type: 'json' };
import duskfox from './duskfox.json' with { type: 'json' };
import nightfox from './nightfox.json' with { type: 'json' };
import nordfox from './nordfox.json' with { type: 'json' };
import terafox from './terafox.json' with { type: 'json' };
import dawnfox from './dawnfox.json' with { type: 'json' };
import dayfox from './dayfox.json' with { type: 'json' };
import synthwave84 from './synthwave-84.json' with { type: 'json' };
import cobalt2 from './cobalt2.json' with { type: 'json' };
import oceanicNext from './oceanic-next.json' with { type: 'json' };
import zenburn from './zenburn.json' with { type: 'json' };
import icebergDark from './iceberg-dark.json' with { type: 'json' };
import icebergLight from './iceberg-light.json' with { type: 'json' };
import flexokiDark from './flexoki-dark.json' with { type: 'json' };
import flexokiLight from './flexoki-light.json' with { type: 'json' };
import poimandres from './poimandres.json' with { type: 'json' };
import oxocarbonDark from './oxocarbon-dark.json' with { type: 'json' };
import oxocarbonLight from './oxocarbon-light.json' with { type: 'json' };
import horizonDark from './horizon-dark.json' with { type: 'json' };
import horizonLight from './horizon-light.json' with { type: 'json' };
import type { ThemeDefinition } from '../format.ts';

export default [
  gruvboxDarkHard,
  gruvboxDarkMedium,
  gruvboxDarkSoft,
  gruvboxLightHard,
  gruvboxLightMedium,
  gruvboxLightSoft,
  catppuccinFrappe,
  catppuccinMacchiato,
  catppuccinMocha,
  catppuccinLatte,
  tokyoNight,
  tokyoNightMoon,
  tokyoNightStorm,
  tokyoNightDay,
  dracula,
  draculaAlucard,
  nord,
  solarizedDark,
  solarizedLight,
  oneDark,
  oneLight,
  rosePine,
  rosePineMoon,
  rosePineDawn,
  githubDark,
  githubDarkDimmed,
  githubDarkHighContrast,
  githubLight,
  githubLightHighContrast,
  kanagawaDragon,
  kanagawaWave,
  kanagawaLotus,
  everforestDarkHard,
  everforestDarkMedium,
  everforestDarkSoft,
  everforestLightHard,
  everforestLightMedium,
  everforestLightSoft,
  monokai,
  ayuDark,
  ayuMirage,
  ayuLight,
  nightOwl,
  lightOwl,
  material,
  materialDarker,
  materialDeepOcean,
  materialOceanic,
  materialPalenight,
  materialLighter,
  tomorrowNight,
  tomorrowNightBlue,
  tomorrowNightBright,
  tomorrowNightEighties,
  tomorrow,
  carbonfox,
  duskfox,
  nightfox,
  nordfox,
  terafox,
  dawnfox,
  dayfox,
  synthwave84,
  cobalt2,
  oceanicNext,
  zenburn,
  icebergDark,
  icebergLight,
  flexokiDark,
  flexokiLight,
  poimandres,
  oxocarbonDark,
  oxocarbonLight,
  horizonDark,
  horizonLight,
] as ThemeDefinition[];
