// Tools for the built-in theme files in src/themes/builtin/.
//
//   npm run themes -- derive <file.json...>   fill in colors that follow from others (soft tints, text on
//                                             fills, …) where a file leaves them out, and rewrite the
//                                             file in canonical order. Colors already given are kept.
//   npm run themes -- check [file.json...]    validate the format and legibility (all files by default)
//   npm run themes -- index                   regenerate src/themes/builtin/index.ts from the folder

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { contrastRatio, parseColor, toOklch } from '../src/shared/color.ts';
import { derivedColor, FIELDS, GROUP_LABELS, legibilityRules, validateTheme } from '../src/themes/format.ts';

const DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../src/themes/builtin');

/** Picker order of families; unknown families come after, alphabetically. */
const FAMILY_ORDER = [
  'Gruvbox', 'Catppuccin', 'Tokyo Night', 'Dracula', 'Nord', 'Solarized', 'One', 'Rosé Pine', 'GitHub',
  'Kanagawa', 'Everforest', 'Monokai', 'Ayu', 'Night Owl', 'Material', 'Tomorrow', 'Nightfox',
  'Synthwave', 'Cobalt2', 'Oceanic Next', 'Zenburn', 'Iceberg', 'Flexoki', 'Poimandres', 'Oxocarbon', 'Horizon',
];

const files = (args) => (args.length ? args.map((f) => path.resolve(f)) : fs.readdirSync(DIR).filter((f) => f.endsWith('.json')).map((f) => path.join(DIR, f)));
const read = (file) => JSON.parse(fs.readFileSync(file, 'utf8'));

function canonical(theme) {
  const out = { $schema: '../theme.schema.json', format: 1, id: theme.id, name: theme.name };
  if (theme.family) out.family = theme.family;
  out.mode = theme.mode;
  for (const group of Object.keys(GROUP_LABELS)) {
    out[group] = {};
    for (const f of FIELDS.filter((x) => x.group === group)) if (theme[group]?.[f.key] !== undefined) out[group][f.key] = theme[group][f.key];
  }
  return out;
}

function derive(args) {
  for (const file of files(args)) {
    const theme = read(file);
    for (const group of Object.keys(GROUP_LABELS)) theme[group] ??= {};
    let filled = 0;
    // Tints and on-fill colors depend on other colors, so fill until nothing changes.
    for (let pass = 0; pass < 3; pass++) {
      for (const f of FIELDS) {
        if (theme[f.group][f.key] !== undefined) continue;
        const value = derivedColor(theme, f.group, f.key);
        if (value !== undefined) {
          theme[f.group][f.key] = value;
          filled++;
        }
      }
    }
    fs.writeFileSync(file, JSON.stringify(canonical(theme), null, 2) + '\n');
    console.log(`${path.basename(file)}: filled ${filled} derived color${filled === 1 ? '' : 's'}`);
  }
}

function check(args) {
  const list = files(args);
  const ids = new Map();
  let failures = 0;
  for (const file of list) {
    const theme = read(file);
    const problems = validateTheme(theme);
    if (!problems.length) {
      if (path.basename(file) !== `${theme.id}.json`) problems.push(`file name should be ${theme.id}.json`);
      if (ids.has(theme.id)) problems.push(`id "${theme.id}" is also used by ${ids.get(theme.id)}`);
      ids.set(theme.id, path.basename(file));
      const pageL = toOklch(parseColor(theme.background.page)).l;
      if ((theme.mode === 'dark') !== pageL < 0.5) problems.push(`mode is "${theme.mode}" but the page color is ${pageL < 0.5 ? 'dark' : 'light'}`);
      for (const [label, fg, bg, min] of legibilityRules(theme)) {
        const ratio = contrastRatio(parseColor(fg), parseColor(bg));
        if (ratio < min) problems.push(`${label}: ${ratio.toFixed(2)}:1 (needs ${min}:1) — ${fg} on ${bg}`);
      }
    }
    if (problems.length) {
      failures++;
      console.log(`✗ ${path.basename(file)}\n  ${problems.join('\n  ')}`);
    } else {
      console.log(`✓ ${path.basename(file)}`);
    }
  }
  console.log(`\n${list.length - failures}/${list.length} themes pass.`);
  if (failures) process.exitCode = 1;
}

function index() {
  const themes = files([]).map((file) => ({ file: path.basename(file), theme: read(file) }));
  const rank = (family) => {
    const i = FAMILY_ORDER.indexOf(family);
    return i < 0 ? FAMILY_ORDER.length : i;
  };
  themes.sort(
    (a, b) =>
      rank(a.theme.family) - rank(b.theme.family) ||
      (a.theme.family ?? '').localeCompare(b.theme.family ?? '') ||
      (a.theme.mode === b.theme.mode ? 0 : a.theme.mode === 'dark' ? -1 : 1) ||
      a.file.localeCompare(b.file),
  );
  const name = (file) => file.replace(/\.json$/, '').replace(/-(\w)/g, (_, c) => c.toUpperCase()).replace(/^(\d)/, '_$1');
  const lines = [
    '// Generated by `npm run themes -- index` from the JSON files in this folder. Do not edit.',
    '',
    ...themes.map(({ file }) => `import ${name(file)} from './${file}' with { type: 'json' };`),
    "import type { ThemeDefinition } from '../format.ts';",
    '',
    'export default [',
    ...themes.map(({ file }) => `  ${name(file)},`),
    '] as ThemeDefinition[];',
    '',
  ];
  fs.writeFileSync(path.join(DIR, 'index.ts'), lines.join('\n'));
  console.log(`index.ts lists ${themes.length} themes`);
}

const [command, ...args] = process.argv.slice(2);
if (command === 'derive') derive(args);
else if (command === 'check') check(args);
else if (command === 'index') index();
else {
  console.error('usage: npm run themes -- derive <files…> | check [files…] | index');
  process.exitCode = 2;
}
